<a href="https://colab.research.google.com/github/SharonCamacho/Clases/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

*Tomado de **Python Data Science Handbook** de Jake VanderPlas*

*   Proveniente de Numerical Python
*   Estructura de datos propia: los arrays que hace más eficiente el manejo de datos



In [2]:
#Importamos la librería
import numpy as np

In [2]:
numpy.__version__
#Genera un error porque cuando importé la librería 
#indiqué que iba a usar un alias

NameError: ignored

In [5]:
np.__version__

'1.18.5'

In [6]:
#para tener información acerca de numpy
np?

In [7]:
#Ejemplo
np.max?

## Crear **arrays**

No olvides que los arrays solo contienen un tipo de datos

In [8]:
# Crear un array de enteros:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [9]:
#Como solo puede contener un tipo de datos los int se convierten en float
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [10]:
#Si queremos especificar el tipo podemos usar dtipe
np.array([3.14, 4, 2, 3], dtype='int')

array([3, 4, 2, 3])

A diferencia de las listas de Python, las matrices NumPy pueden ser explícitamente multidimensionales

In [11]:
# Una lista de lista me da un array multidimensional
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

>>> ***OJO AQUÍ EXPLICAR LIST COMPRENHENCIÖN***

## Crear arrays DUMMIES desde cero 

Es más eficiente crear matrices desde cero usando rutinas integradas en NumPy.

In [12]:
# Crear un array de longitud 10 lleno con 0
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
# Crear un array de 3X5 llenado con 1 tipo flotante
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
# Crear un array de 3X5 llenado con 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
# Crear un array con una secuencia
# Inica en 0, termina en 20 con pasos de 2

np.arange(0, 20, 2)

#Notar que el 20 no es incluyente

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
# Cree un array de cinco valores espaciados uniformemente entre 0 y 1
np.linspace(0, 1, 5)

#Aquí el 1 es incluyente

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
# Cree un array de 3x3 de distribución uniforme
# Valores aleatorios entre 0 y 1 

np.random.random((3, 3))

array([[0.93953023, 0.15738533, 0.88286553],
       [0.7723468 , 0.85694514, 0.71728464],
       [0.84398222, 0.01335731, 0.55065689]])

>> # **Agregar foto de distribución uniforme**





In [18]:
# Cree un array de 3x3 de distribución normal
# Valores aleatorios con media 0 y desviación estandar 1 

np.random.normal(0, 1, (3, 3))

array([[ 0.32648678, -0.72606178, -0.56779108],
       [-0.20434653, -0.18033496, -0.89287188],
       [-1.61745905,  0.41509747,  0.23666678]])

>> # **Agregar foto de distribución normal**

In [19]:
# Cree un array de 3x3
# con enteros aleatorios en un intervalo de [0,10)
np.random.randint(0, 10, (3, 3))

array([[2, 9, 4],
       [8, 3, 1],
       [1, 5, 5]])

In [20]:
# Crre un array 3x3 con la matriz identidad
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# Cree una matriz no inicializada de tres enteros
# Los valores serán lo que suceda que ya exista en esa ubicación de memoria
np.empty(3)

array([1., 1., 1.])

In [4]:
np.empty?


"vacío, a diferencia de los ceros, no establece los valores de la matriz en cero y, por lo tanto, puede ser ligeramente más rápido. Por otro lado, requiere que el usuario establezca manualmente todos los valores de la matriz y debe usarse con precaución" (https://bit.ly/3iKLKaV)

## Lo básico de los array

### Atributos

In [22]:
#Creamos una semilla para obtener los mismos resultados
np.random.seed(0)

In [90]:
#Creo un array
x3 = np.random.randint(10, size=(3, 4, 5))

In [91]:
x3
#observar que no trae valores mayores a 10

array([[[7, 9, 1, 9, 6],
        [0, 3, 8, 4, 1],
        [4, 5, 0, 3, 1],
        [4, 4, 4, 0, 0]],

       [[8, 4, 6, 9, 3],
        [3, 2, 1, 2, 1],
        [3, 4, 1, 1, 0],
        [7, 8, 4, 3, 5]],

       [[6, 3, 2, 9, 8],
        [1, 4, 0, 8, 3],
        [9, 5, 5, 1, 7],
        [8, 6, 4, 7, 3]]])

In [47]:
#Muestro los atributos de ese array
print("x3 dimensión: ", x3.ndim)
print("x3 forma:", x3.shape)
print("x3 tamaño: ", x3.size)
print("x3 tipo de dato: ", x3.dtype)

x3 dimensión:  3
x3 forma: (3, 4, 5)
x3 tamaño:  60
x3 tipo de dato:  int64


In [48]:
print("itemsize:", x3.itemsize, "bytes") #Tamaño de cada elemento
print("nbytes:", x3.nbytes, "bytes") #Tamaño del array

itemsize: 8 bytes
nbytes: 480 bytes


### Indexación

In [52]:
x3

array([[[7, 8, 5, 0, 8],
        [5, 4, 7, 4, 1],
        [3, 3, 9, 2, 5],
        [2, 3, 5, 7, 2]],

       [[7, 1, 6, 5, 0],
        [0, 3, 1, 9, 9],
        [6, 6, 7, 8, 8],
        [7, 0, 8, 6, 8]],

       [[9, 8, 3, 6, 1],
        [7, 4, 9, 2, 0],
        [8, 2, 7, 8, 4],
        [4, 1, 7, 6, 9]]])

In [49]:
x3[1]

array([[7, 1, 6, 5, 0],
       [0, 3, 1, 9, 9],
       [6, 6, 7, 8, 8],
       [7, 0, 8, 6, 8]])

In [50]:
x3[1][2]

array([6, 6, 7, 8, 8])

In [51]:
x3[1][2][2]

7

In [53]:
x3[1][2][-1]

8

In [56]:
x3[1,2,2]

7

In [59]:
x3[1,2,2] = 20.892
x3[1,2]

array([ 6,  6, 20,  8,  8])

### Slicing

x[start : stop : step]

si no se especifican los valores start=0, stop=tamaño de la dimensión, step=1


cuando trabajamos con grandes conjuntos de datos, podemos acceder y procesar partes de estos conjuntos de datos sin la necesidad de copiar el búfer de datos subyacente.

#### De una dimensión

In [60]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5]  # first five elements

In [ ]:
x[5:]  # elements after index 5

In [ ]:
x[4:7]  # middle sub-array

In [ ]:
x[::2]  # every other element

In [ ]:
x[::-1]  # all elements, reversed

#### Varias dimensiones

In [64]:
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x2

array([[4, 1, 5, 9],
       [7, 1, 3, 5],
       [7, 3, 6, 6]])

In [65]:
x2[:2, :3]  # two rows, three columns

array([[4, 1, 5],
       [7, 1, 3]])

In [74]:
#Las dos primeras filas
x2[:2]

array([[4, 1, 5, 9],
       [7, 1, 3, 5]])

In [73]:
#Las dos últimas columnas
x2[:,-2:]

array([[5, 9],
       [3, 5],
       [6, 6]])

como sería sacar un cubo de 2x2x2

In [66]:
x3

array([[[ 7,  8,  5,  0,  8],
        [ 5,  4,  7,  4,  1],
        [ 3,  3,  9,  2,  5],
        [ 2,  3,  5,  7,  2]],

       [[ 7,  1,  6,  5,  0],
        [ 0,  3,  1,  9,  9],
        [ 6,  6, 20,  8,  8],
        [ 7,  0,  8,  6,  8]],

       [[ 9,  8,  3,  6,  1],
        [ 7,  4,  9,  2,  0],
        [ 8,  2,  7,  8,  4],
        [ 4,  1,  7,  6,  9]]])

In [68]:
x3_new = x3[:2,:2,:2]

In [70]:
print("x3_new ndim: ", x3_new.ndim)
print("x3_new shape:", x3_new.shape)
print("x3_new size: ", x3_new.size)

x3_new ndim:  3
x3_new shape: (2, 2, 2)
x3_new size:  8


### Reshaping

In [75]:
#Convertirlo en 3x3
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
#Antes era un vector
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
#Mi array incial debe permitir tener esa una forma, porque de lo contrario
#Muestra error

grid2 = np.arange(1, 8).reshape((3, 3))
print(grid2)

#No tiene elementos suficientes para construir una matriz 3x3

ValueError: ignored

### Join / Concatenation

* np.concatenate
* np.vstack
* np.hstack

np.concatenate toma una lista o una tupla como el primer argumento

#### np.concatenate

In [80]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [81]:
#Se pueden concatenar más de dos
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [83]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [84]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [85]:
# concatenate along the first axis
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

#### np.vstack / np.hstack

para arrays con diferentes dimensiones 

el orden importa y las dimensiones también

In [89]:
#Vertical
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [87]:
#Horizontar
y = np.array([[99],
              [99]])
np.hstack([grid, y])

#notar que el orden importa

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])